-- APAGANDO O BANCO DE DADOS CASO EXISTA
DROP DATABASE IF EXISTS DBEXERCICIO_12;

-- CRIANDO O BANCO DE DADOS
CREATE DATABASE DBEXERCICIO_12;

-- CONECTANDO NA BASE DE DADOS
USE DBEXERCICIO_12;

-- CRIANDO AS TABELAS
CREATE TABLE DOCUMENTO_VEICULO (
	IDVEICULO INT NOT NULL 
    , MARCAR VARCHAR(100) NOT NULL
    , MODELO VARCHAR(100) NOT NULL
    , ANO_FABRICACAO INT NOT NULL
    , PLACA VARCHAR(10) NOT NULL
    , IDDOCUMENTO INT 
    , DTREGISTRO DATE
    , RENAVAM INT 
    , CIDADE VARCHAR(100)
    , ESTADO CHAR(2)
	, PRIMARY KEY (IDVEICULO, IDDOCUMENTO)
);
