-- APAGANDO A BANCO DE DADOS
DROP DATABASE IF EXISTS DBEXERCICIO_09;

-- CRIANDO A BASE DA DADOS
CREATE DATABASE DBEXERCICIO_09;

-- CONECTANDO NA BASE DE DADOS
USE DBEXERCICIO_09;

-- CRIANDO A TABELA
CREATE TABLE ELEITOR (
IDELEITOR INT NOT NULL,
 NOME VARCHAR(140) NOT NULL,
 EMAIL VARCHAR(140),
 ANIVERSARIO DATE,
 CEP VARCHAR(45),
 ESTADO VARCHAR(45),
 CIDADE VARCHAR(120),
 BAIRRO VARCHAR(120),
 RUA VARCHAR(120),
 COMPLEMENTO VARCHAR(45),
 NUMERO VARCHAR(45),
 TELEFONE_1 VARCHAR(45),
 TELEFONE_2 VARCHAR(45),
 TELEFONE_3 VARCHAR(45),
 SEXO VARCHAR(45),
 PRIMARY KEY (IDELEITOR)
);